name: Host Service CI

on:
  push:
    branches: [ "main" ]
    paths: ["*.js"]

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps: 
    - name: 1. Checkout 
      uses: actions/checkout@v3
    
    - name: 2. Login to DockerHub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: 3. Build and push 
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: hyeop29/hostservice:${{ github.sha }}
  updateYaml:
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v3
        with:
          repository: 'hyeop29/hostsvc-cd'
          token: ${{ secrets.GITHAB_TOEKN }}
      - name: 2. Change Docker Tag
        run: |
          sed -i "s/image: hyeop29\/node-app:.*/images: hyeop29\/node-app:${{ github.sha }}/g hostservice-deploy.yaml" 
          git config --global user.email "3110ch@naver"
          git config --global user.name "hyeop29"
          git commit -am "triggered by github action"
          git push origin main
